### ISSUE TITLE
异常错误，每隔几秒就会有错误日志

### ISSUE THREAD

**Issue by chenjiabin** [dcat-admin/operation-log#8]
[2022-06-02 11:36:07] local.ERROR: Uncaught Symfony\Component\Finder\Exception\DirectoryNotFoundException: The "" directory does not exist. in .../vendor/symfony/finder/Finder.php:590
Stack trace:
#0 /vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(549): Symfony\Component\Finder\Finder->in()
#1 Command line code(1): Illuminate\Filesystem\Filesystem->files()
#2 Command line code(1): getViews()
#3 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Symfony\\Component\\Finder\\Exception\\DirectoryNotFoundException: The \"//dcat-admin-extensions/dcat-admin/operation-log/resources/views\" directory does not exist. in /vendor/symfony/finder/Finder.php:590
Stack trace:
#0 /vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(549): Symfony\\Component\\Finder\\Finder->in()
#1 Command line code(1): Illuminate\\Filesystem\\Filesystem->files()
#2 Command line code(1): getViews()
#3 {main}
  thrown at /vendor/symfony/finder/Finder.php:590)
[stacktrace]
#0 {main}
"} 

php 8.0.18
laravel版本 9.12.2
dcat v2.2.0-beta

**Comment by chenjiabin** [comment]
在operation-log/resources/ 新建views目录 就可以解决
